name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Debug APK
        run: gradle assembleDebug

      - name: Save APK File
        uses: actions/upload-artifact@v4
        with:
          name: my-app-apk
          path: app/build/outputs/apk/debug/app-debug.apk
